name: Build Demo

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.access_token }}
          BRANCH: gh-pages
          FOLDER: 'dist-docs'
          BUILD_SCRIPT: npm ci && npm run build:example
